language: node_js
node_js:
- '0.10'
services:
- mongodb
before_script:
- npm install gulp -g
deploy:
  provider: heroku
  api_key:
    secure: A3aL5P0SVJWd8rh5xd+H5mCx6W0AanePd5TzRfkygvM0NuSS0xzNl126WrFwoFxVFd1Wb32QDVR7cJoH9BSJCBvgXyb2JI2WpFHTlReZumi2HrfGwF5sttFlpOrmgbSvhj0qabgWaQbwMAtIG9wdH88sskYE14d86wJD0wbNrJk=
  app: pullup
  on:
    repo: larvalabs/pullup
